name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - uses: actions/checkout@v2
      - name: 🛠️ Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: 📦 Install dependencies
        run: npm ci
      - name: 🖋️ Format code
        run: npm run format
      - name: 🧹 Lint code
        run: npm run lint
      - name: 🔨 Build
        run: npm run build
      - name: 🧪 Test with coverage
        run: npm run test
